### ISSUE TITLE
How to list all available songs in music_directory

### ISSUE THREAD

**Issue by anhsirk0** [mamantoha/crystal_mpd#20]
with `mpc ls` we can list every song in music_directory.
Is there a way to do that with crystal_mpd?

**Comment by mamantoha** [comment]
[lsinfo](https://mamantoha.github.io/crystal_mpd/MPD/Client.html#listall(uri:String?=nil)-instance-method) - lists the contents of the directory `uri` (`/` by default).

```
client = MPD::Client.new
puts client.lsinfo
```

**Comment by anhsirk0** [comment]
Thanks that works.
